name: timed

on:
  schedule: 
    - cron: "*/6 * * * *"

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |-
          git config user.name "parrot"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          echo $(date -u) >> README.md
          git add README.md
          git commit -m "added date $(date -u)"
          git push