name: timed

on:
  workflow_dispatch:
  push:
  schedule: 
    - cron: "0 0 * * *"

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: commit
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          echo "$(date -u)" >> README.md
          echo "" >> README.md
          git add README.md
          git commit -m "added date $(date -u)"
          git push