name: timed

on:
	schedule: 
    - cron: */6 * * * *

jobs:
  print:
    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |-
          git config user.name "parrot"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          echo $(date -u) >> README.md
          git push